hard-code reminders with li classes
turingschool-projects/1610-remember-9 pull request #4
Opened 2017-02-08 18:53 UTC by StephanieEA

## Purpose

The problem is that we need to display reminders on the screen.  
[Issue #1SeeAllReminders](https://github.com/turingschool-projects/1610-remember-9/issues/1])

## Approach

We added an array of reminders and added the classname to the li tag.  

### Learning

We referenced the ember-groceries lesson from school and the ember docs to ensure we were making changes in the correct places.  

### Open Questions and Pre-Merge TODOs

We hard coded the reminders but weren't sure if your intention was to create a ui so that the user could enter reminders.  

### Test coverage 

We made the first acceptance reminder list test, that was already written, pass.

2017-02-08 21:44 UTC, martensonbj requested changes
Few changes - let me know if you have questions on my comments.

2017-02-08 21:44 UTC, martensonbj commented on tests/unit/routes/index-test.js
> +import { moduleFor, test } from 'ember-qunit';
This is file is not necessary - we can delete it.

2017-02-08 21:44 UTC, martensonbj commented on app/routes/index.js
> +import Ember from 'ember';
This logic should live in a `reminders` route. Generate this with `ember g route reminders` and rethink how we are handing our model to the template. The index route/template should only be used if we need default material on a page, in this issue we want our logic to be associated directly with a `reminders` route. 

Secondly, Mirage is generating 5 reminders for you and popping them into your data store. Once you have the reminders route up created, look into how to find records from the store and pass them to the `reminders.hbs` template.

2017-02-08 21:45 UTC, martensonbj commented on app/routes/index.js
> +import Ember from 'ember';
AKA you shouldn't have to hard code in any reminders at this point.

2017-02-08 22:03 UTC, Tman22 commented on app/templates/index.hbs
> +  <ul><li class='spec-reminder-item'>{{reminder}}</li></ul>
The <ul> tag should be outside the {{each}}. Currently you are making 5 <ul> with a single <li> in each.

2017-02-08 23:39 UTC, martensonbj commented on app/templates/index.hbs
> +  <ul><li class='spec-reminder-item'>{{reminder}}</li></ul>
As a follow up - this is ok if you want to treat each reminder as a UL< although I think it makes more sense to treat each reminder as an article with a title (say maybe h2), date (p) and notes (p).

2017-02-09 04:37 UTC, StephanieEA commented
@Tman22 @martensonbj We moved the reminder logic to the reminder route.  We also moved the ul tag outside of the .spec-reminder-item class.  We deleted the unnecessary file.  We added the changes to pull in reminders from mirage. 🎉

2017-02-09 18:16 UTC, martensonbj approved these changes

2017-02-09 18:16 UTC, martensonbj commented on tests/integration/components/reminder-item-test.js
> +import { moduleForComponent, test } from 'ember-qunit';
👍

2017-02-09 18:16 UTC, martensonbj commented on app/router.js
>  });
Good adjustment! Let's clean up the extra lines and comments here now.

2017-02-09 18:18 UTC, martensonbj commented
Looks good! Keep an eye on extra lines/spacing in the next PRs

2017-02-09 18:20 UTC, merged